name: test CI

on:
  push:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create PR
      run: |
        echo "create PR"
        gh pr create -B master -b "test PR" -f -t "Test PR"
