name: test CI

on:
  pull_request:
    types: closed 

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: echo "Running on PR close actions."
    - name: Pushing
      run: |
        echo "new file" > newfile
        git config --global user.name 'Alok'
        git config --global user.email 'aloknigam247@github.com'
        git add .
        git commit -m "add new file"
        git push
